import TicketClass from "./TicketClass";
import DateTime from "./DateTime";
import Guid from "./Guid";

export default interface TicketSearch {
    TicketClassification?: TicketClass[];
    MaxResults?: number;
    TicketID?: number;
    ParentTicketID?: number;
    SearchText?: string;
    FormIDs?: number[];
    StatusIDs?: number[];
    PastStatusIDs?: number[];
    StatusClassIDs?: number[];
    PriorityIDs?: number[];
    UrgencyIDs?: number[];
    ImpactIDs?: number[];
    AccountIDs?: number[];
    TypeIDs?: number[];
    SourceIDs?: number[];
    UpdatedDateFrom?: DateTime;
    UpdatedDateTo?: DateTime;
    UpdatedByUid?: Guid;
    ModifiedDateFrom?: DateTime;
    ModifiedDateTo?: DateTime;
    ModifiedByUid?: Guid;
    StartDateFrom?: DateTime;
    StartDateTo?: DateTime;
    EndDateFrom?: DateTime;
    EndDateTo?: DateTime;
    RespondedDateFrom?: DateTime;
    RespondedDateTo?: DateTime;
    RespondedByUid?: Guid;
    ClosedDateFrom?: DateTime;
    ClosedDateTo?: DateTime;
    ClosedByUid?: Guid;
    RespondByDateFrom?: DateTime;
    RespondByDateTo?: DateTime;
    CloseByDateFrom?: DateTime;
    CloseByDateTo?: DateTime;
    CreatedDateFrom?: DateTime;
    CreatedDateTo?: DateTime;
    CreatedByUid?: Guid;
    DaysOldFrom?: number;
    DaysOldTo?: number;
    ResponsibilityUids?: Guid[];
    ResponsibilityGroupIDs?: number[];
    CompletedTaskResponsibilityFilter?: boolean;
    PrimaryRespoonsibilityUids?: Guid[];
    PrimaryResponsibilityGroupIDs?: number[];
    SlaIDs?: number[];
    SlaViolationStatus?: boolean;
    //SlaUnmetConstraints?: UnmetConstraintSearchType;
    KBArticleIDs?: number[];
    AssignmentStatus?: boolean;
    ConvertedToTask?: boolean;
    ReviewerUids?: Guid[];
    RequestorNameSearch?: string;
    RequestorEmailSearch?: string;
    RequestorPhoneSearch?: string;
    ConfigurationItemIDs?: number[];
    ExcludeConfigurationItemIDs?: number[];
    IsOnHold?: boolean;
    GoesOffHoldFrom?: DateTime;
    GoesOffHoldTo?: DateTime;
    LocationIDs?: number[];
    LocationRoomIDs?: number[];
    ServiceIDs?: number[];
    //CustomAttributes?: CustomAttribute[];
    HasReferenceCode?: boolean;

}