import Guid from "./Guid";
import UserApplication from "./UserApplication";
import DateTime from "./DateTime";
import UserType from "./UserType";
import CustomAttribute from "./CustomAttribute";

export default interface User {
    UID: Guid;
    ReferenceID: number;
    BEID: Guid;
    BEIDInt: number;
    IsActive: boolean;
    IsConfidential: boolean;
    UserName: string;
    FullName: string;
    FirstName: string;
    LastName: string;
    MiddleName?: string;
    Salutation?: string;
    Nickname?: string;
    DefaultAccountID: number;
    PrimaryEmail: string;
    AlternateEmail?: string;
    ExternalID?: string;
    AlternateID?: string;
    Applications?: string[];
    SecurityRoleName: string;
    SecurityRoleID: number;
    Permissions?: string[];
    OrgApplications?: UserApplication[];
    PrimaryClientPortalApplicationID?: number;
    GroupIDs?: number[];
    AlertEmail?: string;
    ProfileImageFileName: string;
    Company: string;
    Title?: string;
    HomePhone?: string;
    PrimaryPhone?: string;
    WorkPhone?: string;
    Pager?: string;
    OtherPhone?: string;
    MobilePhone?: string;
    Fax?: string;
    DefaultPriorityID: number;
    DefaultPriorityName: string;
    AboutMe?: string;
    TechnicianSignature?: string;
    ApplyTechnicianSignatureToUpdatesAndComments: boolean;
    ApplyTechnicianSignatureToReplies: boolean;
    WorkAddress?: string;
    WorkCity?: string;
    WorkState?: string;
    WorkZip?: string;
    WorkCountry?: string;
    HomeAddress?: string;
    HomeCity?: string;
    HomeState?: string;
    HomeZip?: string;
    HomeCountry?: string;
    LocationID: number;
    LocationName: string;
    LocationRoomID: number;
    LocationRoomName: string;
    DefaultRate: number;
    CostRate: number;
    IsEmployee: boolean;
    WorkableHours: number;
    IsCapacityManaged: boolean;
    ReportTimeAfterDate: DateTime;
    EndDate: DateTime;
    ShouldReportTime: boolean;
    ReportsToUID?: string;
    ReportsToFullName: string;
    ResourcePoolID: number;
    ResourcePoolName: string;
    TZID: number;
    TZName: string;
    TypeID: UserType;
    AuthenticationUserName?: string;
    AuthenticationProviderID?: number;
    Attributes?: CustomAttribute[];
    IMProvider?: string;
    IMHandle?: string;

}