# Automatically build the tampermonkey script when a new commit is pushed to the main branch
name: Auto Build on Push

on:
  push:
    branches: [ 'main' ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist